# Generated by Django 6.0.2 on 2026-02-08 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AircraftCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(blank=True, choices=[('Пассажирские', 'Пассажирские'), ('Грузовые', 'Грузовые'), ('Военно-транспортные', 'Военно-транспортные'), ('Боевые', 'Боевые'), ('Учебные', 'Учебные'), ('Специального назначения', 'Специального назначения')], max_length=50, null=True)),
                ('image', models.ImageField(upload_to='categ/')),
            ],
        ),
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='menus/')),
                ('model', models.CharField(max_length=70)),
                ('companys', models.CharField(choices=[('Airbus', 'Airbus'), ('Boeing', 'Boeing'), ('Embraer', 'Embraer'), ('Bombardier', 'Bombardier'), ('ATR', 'ATR'), ('Сухой', 'Сухой'), ('Иркут', 'Иркут'), ('COMAC', 'COMAC'), ('Gulfstream', 'Gulfstream'), ('Dassault', 'Dassault'), ('Cessna', 'Cessna')], max_length=20)),
                ('year_manufacture', models.PositiveIntegerField()),
                ('raid', models.PositiveIntegerField()),
                ('current_rate', models.PositiveIntegerField()),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aircraft', to='core.aircraftcategory')),
            ],
        ),
    ]
