# Generated by Django 6.0.2 on 2026-02-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='menus/')),
                ('name', models.CharField(max_length=70)),
                ('year_manufacture', models.PositiveIntegerField()),
            ],
        ),
    ]
