# Generated by Django 6.0.2 on 2026-02-08 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aircraft',
            old_name='menu',
            new_name='category',
        ),
    ]
