# Generated by Django 6.0.2 on 2026-02-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='current_rate',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aircraft',
            name='raid',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
