# Generated by Django 5.2.11 on 2026-02-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_aircraft_current_rate_aircraft_raid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aircraft',
            old_name='name',
            new_name='model',
        ),
        migrations.AddField(
            model_name='aircraft',
            name='companys',
            field=models.CharField(choices=[('Airbus', 'Airbus'), ('Boeing', 'Boeing'), ('Embraer', 'Embraer'), ('Bombardier', 'Bombardier'), ('ATR', 'ATR'), ('Сухой', 'Сухой'), ('Иркут', 'Иркут'), ('COMAC', 'COMAC'), ('Gulfstream', 'Gulfstream'), ('Dassault', 'Dassault'), ('Cessna', 'Cessna')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
